### PR TITLE
Resolves #931: Fixing problems with encoding in UseDepVersion and PomHelper

### LINKED ISSUE #931: NPE and wrong encoding for umlauts
Hi,

i am using org.codehaus.mojo:versions-maven-plugin in latest version (2.15.0) for updating multiple poms in my project.
Note: When I switch back to version 2.14.2 everything works fine.
Now there are two issues:

**1.** The umlauts in the poms are in wrong encoding after updating:
diff:
       Hinzugefügt
-> HinzugefÃ¼gt

**2.** For one pom I get a NPE with these logs:

[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.15.0:use-dep-version (default-cli) on project migration: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.15.0:use-dep-version failed.: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.15.0:use-dep-version (default-cli) on project migration: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.15.0:use-dep-version failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.15.0:use-dep-version failed.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.NullPointerException
    at org.codehaus.plexus.util.StringUtils.deleteWhitespace (StringUtils.java:147)
    at org.codehaus.mojo.versions.api.PomHelper.setDependencyVersion (PomHelper.java:565)
    at org.codehaus.mojo.versions.AbstractVersionsDependencyUpdaterMojo.updateDependencyVersion (AbstractVersionsDependencyUpdaterMojo.java:536)
    at org.codehaus.mojo.versions.UseDepVersionMojo.useDepVersion (UseDepVersionMojo.java:366)
    at org.codehaus.mojo.versions.UseDepVersionMojo.processModel (UseDepVersionMojo.java:201)
    at org.codehaus.mojo.versions.UseDepVersionMojo.execute (UseDepVersionMojo.java:156)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

### PR DESCRIPTION
**Pull request by ajarmoniuk**
As shown in #931, recent changes introduced in 2.15.0 introduced a regression when the user used irregular characters.

The problem is highly platform dependent and occurs when the `file.encoding` system property does not equal to the one returned by `Charset.defaultCharset()`.

In this particular case, we were using String(byte[]) to construct a String from a byte array which assumed incorrect encoding.

The file was an utf-8 file, but `file.encoding` was equal to `latin1` or `windows1252`. 

@slawekjaranowski please review

### CODE REVIEW

**Comment by ajarmoniuk** [comment]
@slachiewicz please review

File: versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java [hunk 1]
```diff
@@ -150,4 +154,18 @@ public static Dependency interpolateVersion(final Dependency dependency, final M
...
+
+    /**
+     * Reads the given file to a StringBuilder
+     * @param path file path
+     * @return StringBuilder containing the given file
+     * @throws IOException thrown in case of an I/O error
+     */
+    public static StringBuilder readFile(Path path) throws IOException {
+        try (BufferedReader reader = Files.newBufferedReader(path)) {
+            return reader.lines().collect(StringBuilder::new, StringBuilder::append, StringBuilder::append);
```
Comment (slawekjaranowski) [inline versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java:166]: Does line end character can be important here? 
In old implementation we read bytes from file but here line end character can be drop.

Comment (ajarmoniuk) [reply versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java:166]: Easier to debug if tests go wrong, if I remember correctly.

Comment (ajarmoniuk) [reply versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java:166]: Ok, we are not adding any extra new lines here.

I checked and now I remember that: in the old implementation we are reading into a byte array and then converting that byte array to a String using the default encoding. In some systems, e.g. Windows, this produces wrong results resulting in these "umlauts" being incorrect. 

Using a StringBuilder in between is free from this problem. That is the whole fix to this issue.

Comment (ajarmoniuk) [reply versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java:166]: Still in a draft, but for the record: the issue is caused by a *discrepancy between `-Dfile.encoding` and the actual encoding of the file*. The system property determines the value of the `Charset.defaultCharset()` used to convert the bytes[] read in Files.read() into a string using `new String(byte[])`.

Comment (ajarmoniuk) [reply versions-common/src/main/java/org/codehaus/mojo/versions/utils/MavenProjectUtils.java:166]: So, I don't really know whether this is a bug or not. In 2.14.2 it did not need to use the raw file so it relied completely on Maven to process the file. In version 2.15.0, the plugin processes raw POM and thus is susceptible to problems with encoding.

In this case, the problem is caused by the user having the **wrong value of their -Dfile.encoding** system property, which causes String(byte[]) to use the wrong encoding (given by the user) to convert the byte array to string. This is why I also wasn't able to reproduce the issue.

This same problem will occur everywhere where we process raw pom and a user will have a system with the wrong config.

So, as an attempt to solve this problem -- I'm using Plexus's XmlReader with its detection capability to detect the encoding. Please tell me what you think of this solution.

**Comment by ajarmoniuk** [comment]
There's something wrong with GitHub Actions. Could you please restart the CI run? Thanks.

**Comment by slawekjaranowski** [comment]
There is a method - `PomHelper.readXmlFile` looks like we can use it instead of creating next method for xml reading.
I pushed commit  with it.

@ajarmoniuk What do you think?

**Comment by ajarmoniuk** [comment]
> There is a method - `PomHelper.readXmlFile` looks like we can use it instead of creating next method for xml reading. I pushed commit with it.
> 
> @ajarmoniuk What do you think?

Even better! :+1:
